# Generated by Django 4.2.8 on 2025-12-03 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('alert_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DomainStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('first_accessed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Domain Stats',
                'ordering': ['-request_count'],
            },
        ),
        migrations.CreateModel(
            name='ProxyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('url', models.TextField(blank=True, null=True)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('path', models.TextField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(db_index=True, default=0)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_length', models.BigIntegerField(default=0)),
                ('response_time', models.IntegerField(default=0)),
                ('blocked', models.BooleanField(db_index=True, default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('blocked_requests', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('unique_domains', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-hour'],
            },
        ),
    ]
