# Generated by Django 4.2.8 on 2025-12-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPHostnameCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_server', models.CharField(blank=True, max_length=45, null=True)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('resolution_time_ms', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IP Hostname Cache',
                'verbose_name_plural': 'IP Hostname Cache',
            },
        ),
    ]
