# Generated by Django 3.2.25 on 2026-02-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='iphostnamecache',
            name='idx_ipcache_ip',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_timestamp_desc',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_ts_blocked',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_hostname',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_source_ip',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_method',
        ),
        migrations.RemoveIndex(
            model_name='proxyrequest',
            name='idx_proxy_blocked',
        ),
    ]
