# Generated by Django 5.2.12 on 2026-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20260220_1127'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['-timestamp', 'method'], name='dashboard_p_timesta_55cd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['-timestamp', 'status_code'], name='dashboard_p_timesta_51f671_idx'),
        ),
    ]
