# Generated by Django 5.2.12 on 2026-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_proxyrequest_dashboard_p_timesta_55cd7a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['source_ip', '-timestamp'], name='dashboard_p_source__af910d_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['content_length'], name='dashboard_p_content_727a93_idx'),
        ),
    ]
