# Generated by Django 4.2.8 on 2025-12-04 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name for identification', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_ip', models.CharField(default='*', help_text='Source IP: exact (192.168.1.100), CIDR (192.168.1.0/24), or * for any', max_length=50)),
                ('dest_ip', models.CharField(default='*', help_text='Destination IP: exact (10.0.0.5), CIDR (142.250.0.0/16), or * for any', max_length=50)),
                ('source_port', models.CharField(default='*', help_text='Source Port: single (80), range (1024-65535), or * for any', max_length=20)),
                ('dest_port', models.CharField(default='*', help_text='Destination Port: single (443), range (8000-9000), or * for any', max_length=20)),
                ('action', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow')], default='block', max_length=10)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority. Allow rules should have lower priority to override blocks.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BlockedIP',
        ),
        migrations.DeleteModel(
            name='BlockedPort',
        ),
        migrations.DeleteModel(
            name='BlockRule',
        ),
    ]
