# Generated by Django 4.2.8 on 2025-12-03 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockCategory',
        ),
        migrations.AlterModelOptions(
            name='blockeddomain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blocked Domain', 'verbose_name_plural': 'Blocked Domains'},
        ),
        migrations.AddField(
            model_name='blockeddomain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blockeddomain',
            name='category',
            field=models.CharField(choices=[('manual', 'Manual'), ('ads', 'Advertising'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('adult', 'Adult Content'), ('social', 'Social Media'), ('gambling', 'Gambling'), ('other', 'Other')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='blockeddomain',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blockeddomain',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blockeddomain',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='blockeddomain',
            table=None,
        ),
    ]
